CREATE TABLE ESTUDIANTE_TABLE ( ESTUDIANTE_ID TEXT PRIMARY KEY, ESTUDIANTE_NOMBRE TEXT, ESTUDIANTE_APELLIDO TEXT, ESTUDIANTE_PASS TEXT, ESTUDIANTE_ANIO INTEGER);

CREATE TABLE CURSO_TABLE ( CURSO_ID TEXT PRIMARY KEY, CURSO_DESCRIPCION TEXT, CURSO_CREDITOS INTEGER);


CREATE TABLE MATRICULA_TABLE (ESTUDIANTE_ID TEXT NOT NULL, CURSO_ID TEXT NOT NULL,CONSTRAINT MATRICULA_TABLE_PK PRIMARY KEY(ESTUDIANTE_ID,CURSO_ID),CONSTRAINT MATRICULA_TABLE_ESTUDIANTE_FK FOREIGN  KEY (ESTUDIANTE_ID) REFERENCES  ESTUDIANTE_TABLE ( ESTUDIANTE_ID ),CONSTRAINT MATRICULA_TABLE_CURSO_FK FOREIGN  KEY (CURSO_ID) REFERENCES  CURSO_TABLE (CURSO_ID));


